version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8876:80"
        container_name: app_nginx
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: ./_docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            - db
        container_name: app

    db:
        image: postgres:${POSTGRES_VERSION:-15}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        ports:
            - "5435:5432"
        volumes:
            - db_data:/var/lib/postgresql/data:rw
        # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: project_db

volumes:
    db_data:
